# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/dvwa

    steps:
      - checkout
      
      # keep the files around for the scan job
      - persist_to_workspace:
          root: ..
          paths:
            - dvwa
      
  veracode_pipeline_scan:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ~/repo
    

    steps:
        # get the files from the previous job
      - attach_workspace:
          at: .
      - run: 
          name: "Package for upload to Veracode"
          #command: zip -r upload.zip nodegoat
          command: zip -r upload.zip dvwa 

      - run: 
          name: "Run Pipeline Scan for Fast Feedback"
          #command: zip -r upload.zip nodegoat
          command: |
             curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
             unzip -o pipeline-scan-LATEST.zip
             ls
             java -jar pipeline-scan.jar --veracode_api_id=3d43e6c19ba62a029b4d74ef3274f64e --veracode_api_key=bcbf7a5c957bb8495ec1be6dbd71a7b6b7549eaed57bd04a81b9d4ec5f61c3c8d634bc68c8139828d0c714bdb1bac088304391e9043f59207801e6cdc062271e  --fail_on_severity="Very High, High" --file="upload.zip"  --json_output_file="results.json"
  

  # job to upload to Veracode for scanning
  
# serial jobs - need to run 'build' before 'scan'
workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - veracode_pipeline_scan:
          requires:
            - build
      


